### ISSUE TITLE
relative ForwardRef eval

### ISSUE THREAD

**Issue by uriyasama** [beartype/beartype#356]
With the latest version I started getting many of these errors in my code, during our dynamic type check:

beartype.roar.BeartypeDecorHintForwardRefException: Die_if_unbearable() type hint typing.Dict[str, ForwardRef('XXXX')] type hint relative forward reference "XXXX" currently only type-checkable in type hints annotating @beartype-decorated callables and classes. For your own safety and those of the codebases you love, consider canonicalizing this relative forward reference into an absolute forward reference (e.g., replace "XXXX" with "{your_package}.{your_submodule}.XXXX").

I read into your code and understood the reasoning for asking users to use absolute forward reference, but this idealistic approach sadly won't work in our project without constricting our customers.

This is an issue for us, which we currently solve by taking all our complex types, iterating into their type components, and run ForwardRef.eval() on each forwardref component, We are getting our hands dirty just so we won't send any types with ForwardRef to beartype.

Is it possible to circumvent this issue in any other way? Maybe a way to provide you a dictionary of local/global class/functions?

**Comment by leycec** [comment]
That's... **terrible!** Are you on the latest @beartype 0.18.2 release, perchance? If not, please upgrade and your woes will (probably) go away:

```bash
pip install --upgrade beartype
```

If you *have* already upgraded, however, this is calamitous! @beartype definitely should *not* be breaking backward compatibility. **Ever.** If @beartype has broken backward compatibility, please reopen this issue with a minimal working example (MWE). I promise to **immediately** fix whatever awful sin I've committed now.

Until then, I humbly apologize for your recent issues with @beartype. ごめんなさい! :bow:

**Comment by uriyasama** [comment]
This isn't directly related to the new beartype version, updating to the latest version didn't solve my issue.

Handcrafted example of the failure I faced:

`from beartype.door import die_if_unbearable
from typing import Dict
from dataclasses import dataclass

@dataclass
class Settings:
    overrides: Dict[str, "Settings"]

if __name__ == "__main__":
    a = {"hello": Settings(overrides={})}
    die_if_unbearable(a, Dict[str, "Settings"])`
    
The issue I get is:
beartype.roar.BeartypeDecorHintForwardRefException: Die_if_unbearable() type hint typing.Dict[str, ForwardRef('Settings')] type hint relative forward reference "Settings" currently only type-checkable in type hints annotating @beartype-decorated callables and classes. For your own safety and those of the codebases you love, consider canonicalizing this relative forward reference into an absolute forward reference (e.g., replace "Settings" with "{your_package}.{your_submodule}.Settings").

In this example it's really easy to solve. I could replace the text within the forwardRef, but sadly this forwardRef isn't in our code, so we can't change it.

We think that beartype.door functions should accept a dictionary of local/global class/functions as a param that can be used to evaluate ForwardRef.
